CREATE TABLE [dbo].[Booking]
(
	[BookingReference] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[BookedDate] DATETIME2 NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
	[NumberOfPeople] INT NOT NULL,
	[BookingEmail] NVARCHAR(256) NOT NULL,
	[RoomId] UNIQUEIDENTIFIER NOT NULL,
)


