CREATE TABLE [dbo].[Room]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[HotelId] UNIQUEIDENTIFIER NOT NULL,
	[RoomType] NVARCHAR(50) NOT NULL,
	[Capacity] INT NOT NULL,

	CONSTRAINT [FK_Room_Hotel] FOREIGN KEY ([HotelId]) REFERENCES [dbo].[Hotel]([Id])
)
